spring.application.name=diamond-service
server.port=8081

# gRPC Server configuration
grpc.server.port=9091

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/diamond_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin_password

spring.ai.openai.api-key=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

spring.ai.openai.chat.options.model=gpt-4.1-mini