spring.application.name=diamond-service
server.port=8081

# gRPC Server configuration
grpc.server.port=9091

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/diamond_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin_password
